// =============================================================================
// HarvestFile USDA Program Navigator — Complete Program Catalog
// Phase 33 Build 1 — 43 Programs Across 5 Categories
// Updated for OBBBA (One Big Beautiful Bill Act) signed July 4, 2025
// =============================================================================

import { USDAProgram } from './types';

export const USDA_PROGRAMS: USDAProgram[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // COMMODITY & SAFETY NET PROGRAMS (FSA)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'arc-co',
    slug: 'arc-co',
    name: 'Agriculture Risk Coverage — County',
    acronym: 'ARC-CO',
    agency: 'FSA',
    category: 'commodity',
    description: 'Revenue-based safety net that triggers payments when actual county crop revenue falls below a guaranteed level. Under OBBBA, the guarantee increased from 86% to 90% of benchmark revenue.',
    eligibilitySummary: 'Must have base acres on file with FSA. Covers 22 commodities. Annual election and enrollment required.',
    estimatedValue: '$0–$155,000/year per person',
    paymentType: 'Direct payment',
    deadlineInfo: 'Annual election deadline typically March 15; enrollment deadline varies. Check with local FSA office.',
    formsRequired: ['CCC-861', 'CCC-862', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/arcplc_program/index',
    learnMoreUrl: 'https://www.harvestfile.com/check',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['price_support', 'risk_management'],
      requiresBaseAcres: true,
    },
    bonusFactors: [
      { field: 'hasCropInsurance', value: true, bonus: 10, reason: 'ARC-CO pairs well with crop insurance for comprehensive coverage' },
    ],
  },

  {
    id: 'plc',
    slug: 'plc',
    name: 'Price Loss Coverage',
    acronym: 'PLC',
    agency: 'FSA',
    category: 'commodity',
    description: 'Price-based safety net that triggers payments when the national marketing year average price falls below the statutory reference price. OBBBA raised reference prices 10–21% across all commodities.',
    eligibilitySummary: 'Must have base acres on file with FSA. Covers 22 commodities. Annual election and enrollment required.',
    estimatedValue: '$0–$155,000/year per person',
    paymentType: 'Direct payment',
    deadlineInfo: 'Annual election deadline typically March 15; enrollment deadline varies.',
    formsRequired: ['CCC-861', 'CCC-862', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/arcplc_program/index',
    learnMoreUrl: 'https://www.harvestfile.com/check',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['price_support', 'risk_management'],
      requiresBaseAcres: true,
    },
  },

  {
    id: 'arc-ic',
    slug: 'arc-ic',
    name: 'Agriculture Risk Coverage — Individual',
    acronym: 'ARC-IC',
    agency: 'FSA',
    category: 'commodity',
    description: 'Individual farm-level revenue protection using your actual yields instead of county averages. Covers 65% of base acres. Best for farms that consistently outperform county yield averages.',
    eligibilitySummary: 'Must have base acres and individual yield history. Covers all commodities on a farm unit.',
    estimatedValue: '$0–$155,000/year per person',
    paymentType: 'Direct payment',
    deadlineInfo: 'Same election/enrollment timeline as ARC-CO and PLC.',
    formsRequired: ['CCC-861', 'CCC-862', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/arcplc_program/index',
    learnMoreUrl: 'https://www.harvestfile.com/check',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['price_support', 'risk_management'],
      requiresBaseAcres: true,
    },
  },

  {
    id: 'dmc',
    slug: 'dairy-margin-coverage',
    name: 'Dairy Margin Coverage',
    acronym: 'DMC',
    agency: 'FSA',
    category: 'commodity',
    description: 'Protects dairy producers when the margin between the all-milk price and feed costs falls below a chosen coverage level. Has paid out in 67% of months since 2018. OBBBA expanded Tier I to 6 million lbs.',
    eligibilitySummary: 'Must be a dairy operation with established production history. Coverage available from $4.00 to $9.50/cwt.',
    estimatedValue: '$0–$100,000+/year depending on production and margin',
    paymentType: 'Direct payment',
    deadlineInfo: '2026 enrollment: January 12 – February 26, 2026. Multi-year lock-in available through 2031 with 25% premium discount.',
    formsRequired: ['CCC-462'],
    applyUrl: 'https://www.fsa.usda.gov/resources/programs/dairy-margin-coverage-program-dmc',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/programs/dairy-margin-coverage-program-dmc',
    conditions: {
      requiresDairy: true,
      relevantNeeds: ['price_support', 'risk_management'],
    },
  },

  {
    id: 'mal',
    slug: 'marketing-assistance-loans',
    name: 'Marketing Assistance Loans',
    acronym: 'MAL',
    agency: 'FSA',
    category: 'commodity',
    description: 'Nine-month interim financing using your harvested crop as collateral. Provides cash flow at harvest when prices may be low, allowing you to sell later at a better price. OBBBA increased loan rates ~10%.',
    eligibilitySummary: 'Must have eligible commodity in storage. Available for most major crops.',
    estimatedValue: 'Loan value depends on production — corn at $2.42/bu, soybeans at $6.82/bu, wheat at $3.72/bu',
    paymentType: 'Loan',
    deadlineInfo: 'Available anytime post-harvest. Loans mature 9 months from date of disbursement.',
    formsRequired: ['CCC-666'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/price-support/Index',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/price-support/Index',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['price_support', 'financing', 'risk_management'],
    },
  },

  {
    id: 'ldp',
    slug: 'loan-deficiency-payments',
    name: 'Loan Deficiency Payments',
    acronym: 'LDP',
    agency: 'FSA',
    category: 'commodity',
    description: 'Direct payment equal to the difference between the county loan rate and posted county price when market prices drop below loan rates. No loan required — just file for the payment.',
    eligibilitySummary: 'Available when posted county price is below the county loan rate. Must have beneficial interest in the commodity.',
    estimatedValue: 'Varies — triggers when prices drop below loan rates',
    paymentType: 'Direct payment',
    deadlineInfo: 'Must apply before losing beneficial interest in the commodity (before selling).',
    formsRequired: ['CCC-633'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/price-support/Index',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/price-support/Index',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['price_support'],
    },
  },

  {
    id: 'fba',
    slug: 'farmer-bridge-assistance',
    name: 'Farmer Bridge Assistance Program',
    acronym: 'FBA',
    agency: 'FSA',
    category: 'commodity',
    description: 'Emergency $12 billion program providing direct payments to farmers impacted by market disruptions from trade actions. One-time assistance based on planted acres and production.',
    eligibilitySummary: 'Must have filed timely acreage reports. Covers producers of covered commodities affected by trade disruptions.',
    estimatedValue: 'Varies by commodity and acreage — potentially $5,000–$100,000+',
    paymentType: 'Direct payment',
    deadlineInfo: 'Enrollment deadline: April 17, 2026.',
    deadlineDate: '2026-04-17',
    formsRequired: ['FSA-578'],
    applyUrl: 'https://www.fsa.usda.gov/resources/income-support/farmer-bridge-assistance-fba-program',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/income-support/farmer-bridge-assistance-fba-program',
    conditions: {
      requiredOperationTypes: ['row_crops', 'livestock', 'dairy', 'specialty_crops'],
      relevantNeeds: ['price_support', 'disaster_recovery'],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONSERVATION PROGRAMS (NRCS & FSA)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'crp-general',
    slug: 'crp-general',
    name: 'Conservation Reserve Program — General',
    acronym: 'CRP General',
    agency: 'FSA',
    category: 'conservation',
    description: 'Retire environmentally sensitive cropland from production for 10–15 years in exchange for annual rental payments. Bids ranked by Environmental Benefits Index. Average payments $57–149/acre.',
    eligibilitySummary: 'Must own or operate eligible cropland that has been planted or considered planted in 4 of 6 prior years.',
    estimatedValue: '$10–$300/acre annually for 10–15 years',
    paymentType: 'Annual rental payment',
    deadlineInfo: '2026 General signup: March 9 – April 17, 2026.',
    deadlineDate: '2026-04-17',
    formsRequired: ['CRP-1', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['conservation'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'crp-continuous',
    slug: 'crp-continuous',
    name: 'Conservation Reserve Program — Continuous',
    acronym: 'CRP Continuous',
    agency: 'FSA',
    category: 'conservation',
    description: 'Non-competitive enrollment for high-priority conservation practices like filter strips, riparian buffers, and grass waterways. Higher payments than General CRP. Accepted year-round.',
    eligibilitySummary: 'Must have eligible land for approved practices. No competitive bidding — automatic acceptance if eligible.',
    estimatedValue: '$100–$300/acre annually with sign-up incentives',
    paymentType: 'Annual rental payment + incentives',
    deadlineInfo: 'Applications accepted year-round. Includes SAFE, CLEAR30, and Farmable Wetlands sub-programs.',
    formsRequired: ['CRP-1', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    conditions: {
      requiredOperationTypes: ['row_crops'],
      relevantNeeds: ['conservation'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'crp-grasslands',
    slug: 'crp-grasslands',
    name: 'Conservation Reserve Program — Grasslands',
    acronym: 'CRP Grasslands',
    agency: 'FSA',
    category: 'conservation',
    description: 'Preserve existing grasslands while allowing continued livestock grazing. Annual rental payments with no requirement to remove land from production. ~9 million acres currently enrolled.',
    eligibilitySummary: 'Must have existing grasslands. Grazing continues — no production restriction.',
    estimatedValue: '$10–$75/acre annually',
    paymentType: 'Annual rental payment',
    deadlineInfo: 'Enrollment period varies annually. Check with local FSA office.',
    formsRequired: ['CRP-1', 'AD-1026'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/conservation-reserve-program/',
    conditions: {
      requiredOperationTypes: ['livestock', 'row_crops'],
      relevantNeeds: ['conservation'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'eqip',
    slug: 'eqip',
    name: 'Environmental Quality Incentives Program',
    acronym: 'EQIP',
    agency: 'NRCS',
    category: 'conservation',
    description: 'Cost-share for 170+ conservation practices on working lands — fencing, irrigation efficiency, nutrient management, cover crops, and more. 75% cost-share (90% for beginning/veteran/underserved). $2.655B funded for FY2026.',
    eligibilitySummary: 'Any agricultural producer. Chronically oversubscribed — strong applications key. At least 50% goes to livestock practices.',
    estimatedValue: '$5,000–$450,000 per contract',
    paymentType: 'Cost-share reimbursement',
    deadlineInfo: 'Applications accepted year-round but ranked in batching cycles. FY2026 primary cutoff was January 15, 2026. Next batching varies by state.',
    formsRequired: ['NRCS-CPA-1200'],
    applyUrl: 'https://www.nrcs.usda.gov/programs-initiatives/eqip-environmental-quality-incentives',
    learnMoreUrl: 'https://www.nrcs.usda.gov/programs-initiatives/eqip-environmental-quality-incentives',
    conditions: {
      relevantNeeds: ['conservation', 'expansion'],
    },
    bonusFactors: [
      { field: 'producerStatuses', value: 'beginning', bonus: 15, reason: 'Beginning farmers receive 90% cost-share and priority ranking' },
      { field: 'producerStatuses', value: 'veteran', bonus: 15, reason: 'Veteran farmers receive 90% cost-share and priority ranking' },
      { field: 'producerStatuses', value: 'socially_disadvantaged', bonus: 15, reason: 'Socially disadvantaged producers receive 90% cost-share, 50% advance payments, and priority ranking' },
    ],
  },

  {
    id: 'csp',
    slug: 'csp',
    name: 'Conservation Stewardship Program',
    acronym: 'CSP',
    agency: 'NRCS',
    category: 'conservation',
    description: 'Rewards existing conservation and incentivizes new practices on working lands. Largest conservation program by acreage (70M+ acres). Five-year contracts with renewal option. $1.3B for FY2026.',
    eligibilitySummary: 'Must already meet stewardship threshold for at least one priority resource concern. Rewards good stewards who want to do more.',
    estimatedValue: '$4,000–$40,000/year for 5 years',
    paymentType: 'Annual stewardship payment',
    deadlineInfo: 'Applications accepted year-round. Ranked in annual batching cycles.',
    formsRequired: ['NRCS-CPA-1200'],
    applyUrl: 'https://www.nrcs.usda.gov/programs-initiatives/csp-conservation-stewardship-program',
    learnMoreUrl: 'https://www.nrcs.usda.gov/programs-initiatives/csp-conservation-stewardship-program',
    conditions: {
      relevantNeeds: ['conservation'],
      hasExistingConservationPlan: true,
    },
  },

  {
    id: 'acep-ale',
    slug: 'acep-ale',
    name: 'Agricultural Conservation Easement — Agricultural Land',
    acronym: 'ACEP-ALE',
    agency: 'NRCS',
    category: 'conservation',
    description: 'Permanent or long-term easements to protect farmland from development. NRCS pays up to 50% of fair market value (75% for significant grasslands). $625M for FY2026.',
    eligibilitySummary: 'Must own eligible farmland under development pressure. Typically requires eligible entity co-holder.',
    estimatedValue: '50–75% of fair market value of easement',
    paymentType: 'One-time easement payment',
    deadlineInfo: 'Applications accepted year-round. Annual ranking and funding cycles.',
    formsRequired: ['NRCS-CPA-1200'],
    applyUrl: 'https://www.nrcs.usda.gov/programs-initiatives/acep-agricultural-conservation-easement-program',
    learnMoreUrl: 'https://www.nrcs.usda.gov/programs-initiatives/acep-agricultural-conservation-easement-program',
    conditions: {
      relevantNeeds: ['conservation'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'acep-wre',
    slug: 'acep-wre',
    name: 'Agricultural Conservation Easement — Wetland Reserve',
    acronym: 'ACEP-WRE',
    agency: 'NRCS',
    category: 'conservation',
    description: 'Restore and protect wetlands through permanent, 30-year, or term easements. Covers up to 100% of value plus 100% of restoration costs for permanent easements.',
    eligibilitySummary: 'Must own farmed or converted wetlands, or lands adjacent to wetlands that contribute to degradation.',
    estimatedValue: '75–100% of land value + restoration costs',
    paymentType: 'One-time easement + restoration cost-share',
    deadlineInfo: 'Applications accepted year-round.',
    formsRequired: ['NRCS-CPA-1200'],
    applyUrl: 'https://www.nrcs.usda.gov/programs-initiatives/acep-agricultural-conservation-easement-program',
    learnMoreUrl: 'https://www.nrcs.usda.gov/programs-initiatives/acep-agricultural-conservation-easement-program',
    conditions: {
      relevantNeeds: ['conservation'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'rcpp',
    slug: 'rcpp',
    name: 'Regional Conservation Partnership Program',
    acronym: 'RCPP',
    agency: 'NRCS',
    category: 'conservation',
    description: 'Leverages public-private partnerships for watershed-scale conservation. Partners include conservation districts, water utilities, and nonprofits. $425M for FY2026.',
    eligibilitySummary: 'Must be in an active RCPP project area. Check with local NRCS for current projects in your county.',
    estimatedValue: 'Varies by project — often enhanced EQIP/CSP rates',
    paymentType: 'Cost-share through partner projects',
    deadlineInfo: 'Varies by project. Contact local NRCS office.',
    formsRequired: ['NRCS-CPA-1200'],
    applyUrl: 'https://www.nrcs.usda.gov/programs-initiatives/rcpp-regional-conservation-partnership-program',
    learnMoreUrl: 'https://www.nrcs.usda.gov/programs-initiatives/rcpp-regional-conservation-partnership-program',
    conditions: {
      relevantNeeds: ['conservation'],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DISASTER ASSISTANCE PROGRAMS (FSA)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'lfp',
    slug: 'livestock-forage-disaster',
    name: 'Livestock Forage Disaster Program',
    acronym: 'LFP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Automatic payments when your county reaches D2 drought for 8+ consecutive weeks (4 weeks for first month under OBBBA) or D3/D4 at any point during grazing season. Up to 60% of feed replacement costs.',
    eligibilitySummary: 'Must own or lease grazing land in a drought-designated county. Livestock must have been on the land during the qualifying period.',
    estimatedValue: '$1,000–$125,000 per person per year',
    paymentType: 'Direct payment',
    deadlineInfo: 'Must file within 30 days of the end of the calendar year in which the loss occurred.',
    formsRequired: ['CCC-853'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-forage/index',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-forage/index',
    conditions: {
      requiredOperationTypes: ['livestock'],
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'lip',
    slug: 'livestock-indemnity',
    name: 'Livestock Indemnity Program',
    acronym: 'LIP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Covers livestock deaths exceeding normal mortality from adverse weather or wildlife attacks. 75% of market value for weather deaths, 100% for predation (OBBBA increase). No payment limit.',
    eligibilitySummary: 'Must have livestock deaths above normal mortality caused by eligible weather events or federally reintroduced wildlife.',
    estimatedValue: '$1,163/head for adult beef cattle (75% of ~$1,550 market value). No payment cap.',
    paymentType: 'Direct indemnity payment',
    deadlineInfo: 'File notice of loss within 30 days of becoming aware of the loss. Application within 30 days of calendar year end.',
    formsRequired: ['CCC-851'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-indemnity/index',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/livestock-indemnity/index',
    conditions: {
      requiredOperationTypes: ['livestock', 'dairy'],
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'elap',
    slug: 'emergency-livestock-assistance',
    name: 'Emergency Assistance for Livestock, Honeybees & Fish',
    acronym: 'ELAP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Covers losses NOT covered by LFP or LIP — feed losses, above-normal transportation costs, grazing losses on non-federal land, honeybee colony losses, and farm-raised fish losses.',
    eligibilitySummary: 'Must have eligible losses not covered by other disaster programs. 15-day notice window for honeybees.',
    estimatedValue: '$500–$125,000 per person per year (combined with LFP)',
    paymentType: 'Direct payment',
    deadlineInfo: 'Notice of loss: 30 days for livestock/fish, 15 days for honeybees. Application: 30 days after calendar year end.',
    formsRequired: ['CCC-851'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/emergency-assist-for-livestock-702702702702702702702702702702702702702702702702702702/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/',
    conditions: {
      requiredOperationTypes: ['livestock', 'honeybees', 'aquaculture', 'dairy'],
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'tap',
    slug: 'tree-assistance',
    name: 'Tree Assistance Program',
    acronym: 'TAP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Cost-share for replanting orchards, vineyards, and nursery stock damaged by natural disasters. OBBBA increased cost-share from 50% to 65% for losses at/below 300% of normal mortality.',
    eligibilitySummary: 'Must have commercially grown trees, bushes, or vines damaged by natural disasters. No payment limit.',
    estimatedValue: '65% of replanting costs (no cap)',
    paymentType: 'Cost-share reimbursement',
    deadlineInfo: 'Must apply within 90 days of the disaster event.',
    formsRequired: ['FSA-840'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/tree-assistance-program/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/tree-assistance-program/',
    conditions: {
      requiredOperationTypes: ['specialty_crops', 'forestry'],
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'nap',
    slug: 'noninsured-crop-disaster',
    name: 'Noninsured Crop Disaster Assistance Program',
    acronym: 'NAP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Crop insurance for crops where federal crop insurance is NOT available — mushrooms, herbs, ginseng, honey, aquaculture, native grass, turfgrass, and many vegetables. $325 service fee per crop per county.',
    eligibilitySummary: 'Must grow a crop for which federal crop insurance is not available. Must purchase BEFORE planting.',
    estimatedValue: 'Catastrophic: 55% of price × losses above 50%. Buy-up: up to 100% of price × losses above 35%.',
    paymentType: 'Indemnity payment',
    deadlineInfo: 'Must purchase BEFORE planting or before coverage period begins. Deadlines vary by crop.',
    formsRequired: ['CCC-471'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/noninsured-crop-disaster-assistance-program/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/noninsured-crop-disaster-assistance-program/',
    conditions: {
      requiredOperationTypes: ['specialty_crops', 'honeybees', 'aquaculture'],
      relevantNeeds: ['risk_management', 'disaster_recovery'],
    },
    bonusFactors: [
      { field: 'hasCropInsurance', value: false, bonus: 20, reason: 'NAP specifically covers crops without federal crop insurance — essential if you lack coverage' },
    ],
  },

  {
    id: 'sdrp',
    slug: 'supplemental-disaster-relief',
    name: 'Supplemental Disaster Relief Program',
    acronym: 'SDRP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Major disaster relief program with ~$16 billion in funding. Stage 1 uses pre-filled applications from existing crop insurance/NAP data. Stage 2 covers non-indemnified and quality losses.',
    eligibilitySummary: 'Must have suffered crop losses in designated disaster years. Must purchase crop insurance or NAP for next 2 crop years.',
    estimatedValue: '$1,000–$500,000+ depending on losses',
    paymentType: 'Direct payment',
    deadlineInfo: 'Stage 1 & 2 deadline: April 30, 2026.',
    deadlineDate: '2026-04-30',
    formsRequired: ['FSA-521'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/disaster-assistance-program/',
    learnMoreUrl: 'https://www.harvestfile.com/sdrp',
    conditions: {
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'ecp',
    slug: 'emergency-conservation',
    name: 'Emergency Conservation Program',
    acronym: 'ECP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Up to 75% cost-share (90% for underserved) to repair farmland damage from natural disasters — debris removal, fence repair, waterway restoration, grading. $500,000 max per person per disaster.',
    eligibilitySummary: 'Must have farmland damaged by a natural disaster in a county where ECP has been authorized.',
    estimatedValue: 'Up to $500,000 per person per disaster (75–90% cost-share)',
    paymentType: 'Cost-share reimbursement',
    deadlineInfo: 'Must apply within the sign-up period announced after disaster designation.',
    formsRequired: ['FSA-244'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/emergency-conservation/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/emergency-conservation/',
    conditions: {
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
    },
    bonusFactors: [
      { field: 'producerStatuses', value: 'socially_disadvantaged', bonus: 10, reason: 'Underserved producers receive 90% cost-share (vs. 75% standard)' },
    ],
  },

  {
    id: 'efrp',
    slug: 'emergency-forest-restoration',
    name: 'Emergency Forest Restoration Program',
    acronym: 'EFRP',
    agency: 'FSA',
    category: 'disaster',
    description: 'Cost-share to restore non-industrial private forest land damaged by natural disasters. Similar structure to ECP but specifically for timber and forestry operations.',
    eligibilitySummary: 'Must own non-industrial private forest land damaged by natural disaster.',
    estimatedValue: 'Up to 75% of restoration costs (90% for underserved)',
    paymentType: 'Cost-share reimbursement',
    deadlineInfo: 'Must apply within the sign-up period announced after disaster designation.',
    formsRequired: ['FSA-244'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/conservation-programs/',
    conditions: {
      requiredOperationTypes: ['forestry'],
      relevantNeeds: ['disaster_recovery'],
      requiresDisasterLoss: true,
      requiresLandOwnership: true,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FSA FARM LOAN PROGRAMS
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'direct-operating',
    slug: 'direct-operating-loan',
    name: 'Direct Farm Operating Loan',
    acronym: 'Direct OL',
    agency: 'FSA',
    category: 'loan',
    description: 'Up to $400,000 at 4.750% for up to 7 years. Covers livestock, seed, fertilizer, equipment, and family living expenses. No bank required — FSA is the direct lender.',
    eligibilitySummary: 'Must be a citizen/legal resident, have acceptable credit history, and be unable to get credit elsewhere at reasonable terms.',
    estimatedValue: 'Up to $400,000 loan at 4.750% interest',
    paymentType: 'Direct loan',
    deadlineInfo: 'Applications accepted year-round at local FSA offices.',
    formsRequired: ['FSA-2001', 'FSA-2037'],
    applyUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-operating-loans',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-operating-loans',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
    },
    bonusFactors: [
      { field: 'producerStatuses', value: 'beginning', bonus: 15, reason: 'Beginning farmers receive reserved funding allocation' },
    ],
  },

  {
    id: 'microloan',
    slug: 'microloan',
    name: 'Farm Operating Microloan',
    acronym: 'Microloan',
    agency: 'FSA',
    category: 'loan',
    description: 'Simplified loan up to $50,000. Accepts alternative experience (small business, internships, apprenticeships). Only 1 year of farm experience required. Streamlined application.',
    eligibilitySummary: 'Same as Direct OL but simplified requirements. Alternative experience counts. Great for small and beginning operations.',
    estimatedValue: 'Up to $50,000 loan at 4.750% interest',
    paymentType: 'Direct loan',
    deadlineInfo: 'Applications accepted year-round.',
    formsRequired: ['FSA-2330'],
    applyUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/microloans',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/microloans',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
    },
    bonusFactors: [
      { field: 'producerStatuses', value: 'beginning', bonus: 20, reason: 'Microloans are specifically designed for small and beginning farmers' },
      { field: 'yearsExperience', value: 0, bonus: 15, reason: 'Only 1 year experience needed — alternative experience accepted' },
    ],
  },

  {
    id: 'direct-ownership',
    slug: 'direct-farm-ownership-loan',
    name: 'Direct Farm Ownership Loan',
    acronym: 'Direct FO',
    agency: 'FSA',
    category: 'loan',
    description: 'Up to $600,000 at 5.875% for up to 40 years. Buy farmland, build structures, improve land, or refinance farm debt. No down payment required for regular loans.',
    eligibilitySummary: 'Must be citizen/legal resident with acceptable credit. 3+ years farming experience required. Cannot get credit elsewhere.',
    estimatedValue: 'Up to $600,000 loan at 5.875% for up to 40 years',
    paymentType: 'Direct loan',
    deadlineInfo: 'Applications accepted year-round.',
    formsRequired: ['FSA-2001', 'FSA-2037'],
    applyUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-ownership-loans',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-ownership-loans',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
    },
  },

  {
    id: 'down-payment',
    slug: 'down-payment-loan',
    name: 'Down Payment Farm Ownership Loan',
    acronym: 'Down Payment',
    agency: 'FSA',
    category: 'loan',
    description: 'Exclusively for beginning and minority/women farmers. FSA finances up to 45% of purchase price (max $300,150) at just 1.875%. You only need 5% cash down.',
    eligibilitySummary: 'Must be a beginning farmer, or a socially disadvantaged or female farmer. 5% down payment required.',
    estimatedValue: 'Up to $300,150 at 1.875% — the best farm financing rate available',
    paymentType: 'Direct loan',
    deadlineInfo: 'Applications accepted year-round. Reserved funding for eligible applicants.',
    formsRequired: ['FSA-2001'],
    applyUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-ownership-loans',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/farm-loan-programs/farm-ownership-loans',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
      requiredProducerStatuses: ['beginning', 'socially_disadvantaged'],
    },
  },

  {
    id: 'guaranteed-loan',
    slug: 'guaranteed-farm-loan',
    name: 'Guaranteed Farm Loan',
    acronym: 'Guaranteed',
    agency: 'FSA',
    category: 'loan',
    description: 'FSA guarantees up to 90% (95% for beginning/underserved) of a commercial loan up to $2,343,000. Access larger loans through your local bank with FSA backing.',
    eligibilitySummary: 'Must work with an approved commercial lender. FSA guarantees the loan, reducing lender risk.',
    estimatedValue: 'Up to $2,343,000 with 90–95% FSA guarantee',
    paymentType: 'Guaranteed loan',
    deadlineInfo: 'Applications accepted year-round through FSA-approved lenders.',
    formsRequired: ['FSA-2211', 'FSA-2254'],
    applyUrl: 'https://www.fsa.usda.gov/resources/loans/guaranteed-farm-loans',
    learnMoreUrl: 'https://www.fsa.usda.gov/resources/loans/guaranteed-farm-loans',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
    },
    bonusFactors: [
      { field: 'producerStatuses', value: 'beginning', bonus: 10, reason: '95% guarantee for beginning farmers (vs. 90% standard)' },
    ],
  },

  {
    id: 'emergency-loan',
    slug: 'emergency-farm-loan',
    name: 'Emergency Farm Loan',
    acronym: 'EM Loan',
    agency: 'FSA',
    category: 'loan',
    description: 'Up to $500,000 at 3.750% for farms suffering 30%+ production or physical losses in designated disaster counties. Below-market rate for disaster recovery.',
    eligibilitySummary: 'Must be in a disaster-designated county with 30%+ loss. Must be unable to get credit elsewhere.',
    estimatedValue: 'Up to $500,000 at 3.750%',
    paymentType: 'Direct loan',
    deadlineInfo: 'Must apply within 8 months of disaster designation.',
    formsRequired: ['FSA-2001'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/emergency-farm-loans/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/emergency-farm-loans/',
    conditions: {
      relevantNeeds: ['financing', 'disaster_recovery'],
      requiresDisasterLoss: true,
    },
  },

  {
    id: 'youth-loan',
    slug: 'youth-loan',
    name: 'Youth Farm Loan',
    acronym: 'Youth Loan',
    agency: 'FSA',
    category: 'loan',
    description: 'Up to $5,000 at 4.750% for ages 10–20 in 4-H, FFA, or similar organizations. Perfect for the next generation of farmers starting their first agricultural project.',
    eligibilitySummary: 'Must be age 10–20 and enrolled in or formerly in 4-H, FFA, or a Tribal youth program. Needs adult sponsor.',
    estimatedValue: 'Up to $5,000 at 4.750%',
    paymentType: 'Direct loan',
    deadlineInfo: 'Applications accepted year-round.',
    formsRequired: ['FSA-2330'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/youth-loans/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/youth-loans/',
    conditions: {
      relevantNeeds: ['financing'],
      maxYearsExperience: 5,
    },
  },

  {
    id: 'land-contract',
    slug: 'land-contract-guarantee',
    name: 'Land Contract Guarantee Program',
    acronym: 'LCG',
    agency: 'FSA',
    category: 'loan',
    description: 'FSA guarantees up to 90% (max $500,000) of a land contract between buyer and seller. Helps beginning and socially disadvantaged farmers buy land from willing sellers without traditional bank financing.',
    eligibilitySummary: 'Buyer must be a beginning or socially disadvantaged farmer. Seller must be willing to enter a land contract.',
    estimatedValue: 'Up to $500,000 guaranteed land contract',
    paymentType: 'Guaranteed land contract',
    deadlineInfo: 'Applications accepted year-round.',
    formsRequired: ['FSA-2211'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/farm-loan-programs/',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
      requiredProducerStatuses: ['beginning', 'socially_disadvantaged'],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPECIALTY, TARGETED & RURAL DEVELOPMENT PROGRAMS
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'occsp',
    slug: 'organic-certification-cost-share',
    name: 'Organic Certification Cost Share Program',
    acronym: 'OCCSP',
    agency: 'FSA',
    category: 'specialty',
    description: 'Reimburses up to 75% of organic certification costs, maximum $750 per scope (crops, livestock, handling, wild crops). Re-funded under OBBBA at $10M/year.',
    eligibilitySummary: 'Must be a certified organic operation or applying for certification.',
    estimatedValue: 'Up to $750 per scope per year',
    paymentType: 'Cost-share reimbursement',
    deadlineInfo: 'Apply through your state USDA office. Annual funding cycle.',
    formsRequired: ['FSA-245'],
    applyUrl: 'https://www.fsa.usda.gov/programs-and-services/occsp/',
    learnMoreUrl: 'https://www.fsa.usda.gov/programs-and-services/occsp/',
    conditions: {
      requiresOrganic: true,
      relevantNeeds: ['organic_transition'],
    },
  },

  {
    id: 'vapg',
    slug: 'value-added-producer-grants',
    name: 'Value-Added Producer Grants',
    acronym: 'VAPG',
    agency: 'RD',
    category: 'specialty',
    description: 'Planning grants up to $75,000 and working capital grants up to $250,000 for value-added activities — direct marketing, processing, agritourism. 1:1 match required.',
    eligibilitySummary: 'Must be an agricultural producer adding value through processing, direct marketing, or farm-based renewable energy.',
    estimatedValue: '$75,000 (planning) or $250,000 (working capital) with 1:1 match',
    paymentType: 'Grant',
    deadlineInfo: 'FY2026 deadline: April 22, 2026. ~$30M available nationally.',
    deadlineDate: '2026-04-22',
    formsRequired: ['SF-424'],
    applyUrl: 'https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants',
    learnMoreUrl: 'https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants',
    conditions: {
      relevantNeeds: ['expansion', 'financing'],
    },
  },

  {
    id: 'reap',
    slug: 'rural-energy-america',
    name: 'Rural Energy for America Program',
    acronym: 'REAP',
    agency: 'RD',
    category: 'specialty',
    description: 'Grants up to $1 million and loan guarantees up to $25 million for renewable energy and energy efficiency improvements. Solar, wind, geothermal, biomass, and efficiency upgrades.',
    eligibilitySummary: 'Agricultural producers deriving 50%+ of gross income from farming. Rural small businesses also eligible.',
    estimatedValue: 'Grants: up to $1M. Loan guarantees: up to $25M.',
    paymentType: 'Grant + loan guarantee',
    deadlineInfo: 'Quarterly application deadlines throughout the year.',
    formsRequired: ['SF-424', 'RD-4274-4'],
    applyUrl: 'https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans',
    learnMoreUrl: 'https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans',
    conditions: {
      relevantNeeds: ['expansion', 'conservation'],
    },
  },

  {
    id: 'bi-loan',
    slug: 'business-industry-loan',
    name: 'Business & Industry Loan Guarantee',
    acronym: 'B&I',
    agency: 'RD',
    category: 'specialty',
    description: 'USDA guarantees up to 80% of commercial loans up to $25 million for rural businesses and agricultural operations. Covers expansion, equipment, working capital, and real estate.',
    eligibilitySummary: 'Must be in a rural area (population under 50,000). Agricultural operations qualify. Work through commercial lender.',
    estimatedValue: 'Up to $25 million with 80% USDA guarantee',
    paymentType: 'Guaranteed loan',
    deadlineInfo: 'Applications accepted year-round through approved lenders.',
    formsRequired: ['RD-4279-1'],
    applyUrl: 'https://www.rd.usda.gov/programs-services/business-programs/business-and-industry-guaranteed-loan',
    learnMoreUrl: 'https://www.rd.usda.gov/programs-services/business-programs/business-and-industry-guaranteed-loan',
    conditions: {
      relevantNeeds: ['financing', 'expansion'],
    },
  },

  {
    id: 'section-2501',
    slug: 'outreach-socially-disadvantaged',
    name: 'Socially Disadvantaged & Veteran Farmers Program',
    acronym: '2501 Program',
    agency: 'NRCS',
    category: 'specialty',
    description: 'Outreach, training, and technical assistance specifically for socially disadvantaged and veteran farmers. Connects you with local organizations providing hands-on support.',
    eligibilitySummary: 'Must be a socially disadvantaged or veteran farmer or rancher.',
    estimatedValue: 'Free training, technical assistance, and mentoring',
    paymentType: 'Technical assistance',
    deadlineInfo: 'Ongoing — contact local organizations.',
    formsRequired: [],
    applyUrl: 'https://www.usda.gov/about-usda/general-information/initiatives-and-highlighted-programs/usda-cares-partner-portal',
    learnMoreUrl: 'https://www.usda.gov/about-usda/general-information/initiatives-and-highlighted-programs/usda-cares-partner-portal',
    conditions: {
      requiredProducerStatuses: ['socially_disadvantaged', 'veteran'],
    },
  },

  {
    id: 'heirs-property',
    slug: 'heirs-property-relending',
    name: "Heirs' Property Relending Program",
    acronym: 'HPRP',
    agency: 'FSA',
    category: 'specialty',
    description: 'Provides capital through intermediary lenders at 1% interest to help resolve title issues for inherited farmland. Critical for multi-generational farms without clear title.',
    eligibilitySummary: 'Must have agricultural land with heirs property title issues.',
    estimatedValue: 'Below-market loans at 1% through intermediary lenders',
    paymentType: 'Relending loan',
    deadlineInfo: 'Contact local FSA office or approved intermediary lenders.',
    formsRequired: [],
    applyUrl: 'https://www.farmers.gov/working-with-us/heirs-property-eligibility/relending',
    learnMoreUrl: 'https://www.farmers.gov/working-with-us/heirs-property-eligibility/relending',
    conditions: {
      relevantNeeds: ['financing'],
      requiresLandOwnership: true,
    },
  },

  {
    id: 'scbg',
    slug: 'specialty-crop-block-grants',
    name: 'Specialty Crop Block Grant Program',
    acronym: 'SCBG',
    agency: 'NRCS',
    category: 'specialty',
    description: 'Approximately $85 million distributed annually through state departments of agriculture. Supports research, marketing, food safety, and production of specialty crops.',
    eligibilitySummary: 'Must grow specialty crops (fruits, vegetables, tree nuts, horticulture, nursery). Apply through your state department of agriculture.',
    estimatedValue: 'Varies by state — typically $25,000–$500,000 per project',
    paymentType: 'Grant (through state)',
    deadlineInfo: 'Varies by state. Check your state department of agriculture.',
    formsRequired: [],
    applyUrl: 'https://www.ams.usda.gov/services/grants/scbgp',
    learnMoreUrl: 'https://www.ams.usda.gov/services/grants/scbgp',
    conditions: {
      requiredOperationTypes: ['specialty_crops'],
      relevantNeeds: ['expansion', 'financing'],
    },
  },

  {
    id: 'fmpp',
    slug: 'farmers-market-promotion',
    name: 'Farmers Market & Local Food Promotion',
    acronym: 'FMLFPP',
    agency: 'NRCS',
    category: 'specialty',
    description: 'Grants for direct-to-consumer marketing channels — farmers markets, community-supported agriculture, food hubs, and local food enterprises. $26.8 million awarded March 2026.',
    eligibilitySummary: 'Agricultural producers, nonprofits, local governments, and cooperatives involved in local food systems.',
    estimatedValue: '$50,000–$500,000 per project',
    paymentType: 'Grant',
    deadlineInfo: 'Annual competitive grant cycle. Check USDA AMS for next cycle.',
    formsRequired: ['SF-424'],
    applyUrl: 'https://www.ams.usda.gov/services/grants/fmpp',
    learnMoreUrl: 'https://www.ams.usda.gov/services/grants/fmpp',
    conditions: {
      relevantNeeds: ['expansion'],
    },
  },
];

// ─── Helper functions ───────────────────────────────────────────────────────

export function getProgramsByCategory(category: string): USDAProgram[] {
  return USDA_PROGRAMS.filter(p => p.category === category);
}

export function getProgramsByAgency(agency: string): USDAProgram[] {
  return USDA_PROGRAMS.filter(p => p.agency === agency);
}

export function getProgramById(id: string): USDAProgram | undefined {
  return USDA_PROGRAMS.find(p => p.id === id);
}

export function getUpcomingDeadlines(): USDAProgram[] {
  const now = new Date();
  return USDA_PROGRAMS
    .filter(p => p.deadlineDate && new Date(p.deadlineDate) > now)
    .sort((a, b) => new Date(a.deadlineDate!).getTime() - new Date(b.deadlineDate!).getTime());
}

export const PROGRAM_CATEGORIES = [
  { id: 'commodity', label: 'Commodity & Safety Net', count: USDA_PROGRAMS.filter(p => p.category === 'commodity').length },
  { id: 'conservation', label: 'Conservation', count: USDA_PROGRAMS.filter(p => p.category === 'conservation').length },
  { id: 'disaster', label: 'Disaster Assistance', count: USDA_PROGRAMS.filter(p => p.category === 'disaster').length },
  { id: 'loan', label: 'Farm Loans', count: USDA_PROGRAMS.filter(p => p.category === 'loan').length },
  { id: 'specialty', label: 'Specialty & Rural Development', count: USDA_PROGRAMS.filter(p => p.category === 'specialty').length },
];

export const TOTAL_PROGRAM_COUNT = USDA_PROGRAMS.length;
